name: discounting
channels:
  - conda-forge
dependencies:
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - contourpy=1.3.3=py312ha0dd364_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - icu=75.1=hfee45f7_0
  - kiwisolver=1.4.9=py312hdc12c9d_1
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.9.0=37_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libcxx=21.1.3=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=37_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libpng=1.6.50=h280e0eb_1
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.1=h7dc4979_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.3=h4a912ad_0
  - matplotlib-base=3.10.6=py312h605b88b_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.3.0=py312h2525f64_3
  - pip=25.2=pyh8b19718_0
  - pthread-stubs=0.4=hd74edd7_1002
  - python=3.12.11=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - statsmodels=0.14.5=py312ha11c99a_1
  - tk=8.6.13=h892fb3f_2
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h163523d_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.0
      - comm==0.2.3
      - debugpy==1.8.16
      - decorator==5.2.1
      - executing==2.2.1
      - fonttools==4.59.2
      - ipykernel==6.30.1
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - pandas==2.3.2
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyzmq==27.1.0
      - scikit-learn==1.7.2
      - scipy==1.16.1
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - wcwidth==0.2.13
prefix: /Users/justinenicholson/miniforge3/envs/discounting
